services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram_bot_api_server
    restart: always
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081" # Открываем порт сервера локально

  telegram-bot:
    build: .
    container_name: videoloader_bot
    restart: always
    depends_on:
      - telegram-bot-api
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      # Передаем боту локальный адрес сервера внутри докер-сети
      - TELEGRAM_API_URL=http://telegram-bot-api:8081
    volumes:
      - ./downloads:/app/downloads
      - ./cookies.txt:/app/cookies.txt

volumes:
  telegram-bot-api-data: